### ISSUE TITLE
Archive aws help

### ISSUE THREAD

**Issue by simonw** [simonw/help-scraper#2]
`aws ...` is a HUGE command.

**Comment by simonw** [comment]
AWS help output is full of this kind of thing:

```
A\x08AV\x08VA\x08AI\x08IL\x08LA\x08AB\x08BL\x08LE\x08E 
```
Turns out that's a trick for applying **bold** by using backspace (`\x08`) to duplicate characters.

After some [Twitter help](https://twitter.com/simonw/status/1487231058261131267) this seems to work for getting rid of those:
```python
backspace_re = re.compile(r'(.)\x08')

def apply_backspaces(s):
    return backspace_re.sub('', s)
```

**Comment by simonw** [comment]
Now running. If this works then the repo is suddenly going to get a LOT bigger.

**Comment by simonw** [comment]
Failed with some very messy looking errors: https://github.com/simonw/help-scraper/runs/4990093130

![EF66ABCC-8215-46E2-B82B-FA781D579D82](https://user-images.githubusercontent.com/9599/151667629-2b66778c-0615-42b9-b18e-e31877746b43.jpeg)

**Comment by simonw** [comment]
Something clearly went wrong with the parser, causing it to try to execute against invalid file names with spaces in them without escaping shell arguments.

**Comment by simonw** [comment]
```
('aws', 'gamelift', 'claim-game-server')
('aws', 'gamelift', 'claim-game-server', 'UTILIZED - The game server is currently hosting a game session')
('aws', 'gamelift', 'accept-match')
('aws', 'fsx')
('aws', 'fsx', 'update-volume')
('aws', 'fsx', 'update-volume', 'UPDATED_OPTIMIZING  -  For  a storage-capacity increase')
('aws', 'fsx', 'update-volume', 'COMPLETED - Amazon FSx has finished processing the  ad-')
('aws', 'fsx', 'update-volume', 'PENDING - Amazon FSx is waiting to process the adminis-')
('aws', 'fsx', 'update-volume', 'IN_PROGRESS - Amazon FSx is processing the  administra-')
('aws', 'fsx', 'update-volume', 'FAILED  -  Amazon FSx failed to process the administra-')
('aws', 'fsx', 'update-volume', 'RELEASE_NFS_V3_LOCKS  -  Tracks  the release of Network')
('aws', 'fsx', 'update-volume', 'SNAPSHOT_UPDATE  -  A  snapshot update to an Amazon FSx')
('aws', 'fsx', 'update-volume', 'VOLUME_UPDATE - A volume update to an  Amazon  FSx  for')
('aws', 'fsx', 'update-volume', 'FILE_SYSTEM_ALIAS_DISASSOCIATION - A file system update')
('aws', 'fsx', 'update-volume', 'FILE_SYSTEM_ALIAS_ASSOCIATION - A file system update to')
('aws', 'fsx', 'update-volume', 'For OpenZFS, storage optimization consists of migrat-')
('aws', 'fsx', 'update-volume', 'For  Lustre,  storage optimization consists of rebal-')
('aws', 'fsx', 'update-volume', 'For  Windows,  storage optimization is the process of')
('aws', 'fsx', 'update-volume', 'STORAGE_OPTIMIZATION  -  After  the  FILE_SYSTEM_UPDATE')
('aws', 'fsx', 'update-volume', 'FILE_SYSTEM_UPDATE - A file system  update  administra-')
('aws', 'fsx', 'update-volume', 'LS specifies a load-sharing mirror volume.  A  load-sharing')
('aws', 'fsx', 'update-volume', 'DP specifies a data-protection volume. You can protect data')
('aws', 'fsx', 'update-volume', 'RW specifies a read/write volume. RW is the default.')
Traceback (most recent call last):
  File "aws_commands.py", line 44, in <module>
    s = fetch_and_save(next_bits)
  File "aws_commands.py", line 33, in fetch_and_save
    (dir / filename).write_text(s, "utf-8")
  File "/usr/lib/python3.8/pathlib.py", line 1255, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'aws/fsx/update-volume/RW specifies a read/write volume. RW is the default..txt'
Error: Process completed with exit code 1.
```
First part of this mystery is:
```
('aws', 'gamelift', 'claim-game-server')
('aws', 'gamelift', 'claim-game-server', 'UTILIZED - The game server is currently hosting a game session')
```
Something on that page got scraped as being a command called `UTILIZED - The game server...`.

**Comment by simonw** [comment]
Here's why: `aws gamelift claim-game-server help` includes the following:
```
       When a game server is successfully claimed, connection  information  is
       returned.  A claimed game server's utilization status remains AVAILABLE
       while the claim status is set to CLAIMED for up  to  60  seconds.  This
       time period gives the game server time to update its status to UTILIZED
       (using  UpdateGameServer ) once players join. If the game server's sta-
       tus  is  not  updated  within  60  seconds,  the game server reverts to
       unclaimed status and is available to be claimed by another request. The
       claim time period is a fixed value and is not configurable.

       If  you  try to claim a specific game server, this request will fail in
       the following cases:

       o If the game server utilization status is UTILIZED .

       o If the game server claim status is CLAIMED .
```
Here's the logic that extracts commands: https://github.com/simonw/help-scraper/blob/3327fefb1d0b484c5b69ad7857949561f119dcb9/aws_commands.py#L12-L17

**Comment by simonw** [comment]
I'm going to switch to looking for `AVAILABLE SERVICES` on the `aws help` index and `AVAILABLE COMMANDS` on other pages.

**Comment by simonw** [comment]
This works now! Would be good to make it faster though.
